-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["banana"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, -3.5  ,  22, 2.5  ,  16, 7.5  ,  14, -0.5  ,  25, -12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16, 7.5  ,  6, 12.5  ,  5, 4.5  ,  14, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25, 4.5  ,  -21, 7.5  ,  -25, 6.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, 12.5  ,  -25, 4.5  ,  5, 4.5  ,  6, 12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21, 7.5  ,  -14, 12.5  ,  -20, 9.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

