-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["ball"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "ball", density = 2, friction = 0.5, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 15.000
                    }
                    
                    
		}
		
		, 
		["char"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -17, -74  ,  -20, -71  ,  -20, -74  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, 69  ,  7, 72  ,  4, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, 69  ,  -25, 72  ,  -28, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -6  ,  -26, -5  ,  -27, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, -63  ,  -27, -62  ,  -27, -63  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, -68  ,  -24, -66  ,  -24, -68  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, -71  ,  -21, -70  ,  -21, -71  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16, -75  ,  -17, -74  ,  -17, -75  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -72  ,  12, -73  ,  13, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   18, -68  ,  16, -70  ,  18, -70  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, -66  ,  18, -68  ,  20, -68  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   22, -64  ,  20, -66  ,  22, -66  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, -32  ,  26, -34  ,  28, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, 72  ,  25, 74  ,  11, 75  ,  26, 56  ,  28, 56  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, 72  ,  8, 73  ,  7, 73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, 68  ,  4, 69  ,  3, 69  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 70  ,  -29, 61  ,  0, 68  ,  0, 70  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25, 72  ,  -24, 73  ,  -25, 73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -24, -66  ,  -26, -63  ,  -26, -66  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -11, -78  ,  -14, -76  ,  -14, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   10, -74  ,  7, -76  ,  10, -76  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16, -70  ,  13, -72  ,  16, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, -61  ,  22, -64  ,  24, -64  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   22, -40  ,  1, -78  ,  24, -43  ,  24, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26, -34  ,  23, -36  ,  26, -36  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 74  ,  28, 72  ,  28, 74  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5, 72  ,  -2, 70  ,  -2, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, 58  ,  3, 68  ,  -28, 61  ,  -28, 58  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21, -70  ,  -22, -68  ,  -22, -70  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, -76  ,  -16, -75  ,  -16, -76  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12, -73  ,  10, -74  ,  12, -74  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, -38  ,  1, -78  ,  22, -40  ,  22, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, -36  ,  21, -37  ,  23, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26, 56  ,  11, 75  ,  25, 54  ,  26, 54  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25, 56  ,  3, 68  ,  -26, 58  ,  -26, 56  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25, 0  ,  -25, 54  ,  -26, 54  ,  -26, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, -41  ,  1, -79  ,  -25, -2  ,  -26, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -9  ,  -27, -6  ,  -28, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, -12  ,  -28, -9  ,  -29, -9  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -46  ,  -22, -68  ,  1, -79  ,  -26, -43  ,  -27, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -49  ,  -26, -63  ,  -24, -66  ,  -22, -68  ,  -27, -46  ,  -28, -46  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -62  ,  -28, -59  ,  -28, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, -77  ,  1, -78  ,  4, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, -76  ,  4, -77  ,  7, -77  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, -9  ,  21, -37  ,  29, -12  ,  29, -9  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27, -6  ,  21, -37  ,  28, -9  ,  28, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26, -3  ,  21, -37  ,  27, -6  ,  27, -3  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 0  ,  21, -37  ,  26, -3  ,  26, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, 3  ,  21, -37  ,  25, 0  ,  25, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, 6  ,  21, -37  ,  24, 3  ,  24, 6  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, 17  ,  23, 14  ,  24, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26, 52  ,  25, 52  ,  25, 32  ,  26, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, 73  ,  11, 74  ,  8, 74  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, 74  ,  -28, 69  ,  -29, 61  ,  -10, 73  ,  -10, 74  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -24, 73  ,  -21, 74  ,  -24, 74  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10, 73  ,  -5, 72  ,  -5, 73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10, 73  ,  -29, 61  ,  -2, 70  ,  -5, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, 72  ,  28, 72  ,  28, 58  ,  30, 58  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, -12  ,  -26, -41  ,  -26, -5  ,  -27, -6  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, -63  ,  -28, -49  ,  -28, -59  ,  -27, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, 68  ,  21, -37  ,  11, 74  ,  8, 73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, 69  ,  -13, 74  ,  -21, 74  ,  -24, 73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, -41  ,  -29, -12  ,  -30, -12  ,  -30, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21, 75  ,  -21, 74  ,  -13, 74  ,  -13, 75  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, 61  ,  -28, 69  ,  -29, 69  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16, -75  ,  -14, -76  ,  1, -79  ,  -22, -68  ,  -21, -70  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -72  ,  25, -43  ,  24, -43  ,  1, -78  ,  7, -76  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -72  ,  10, -74  ,  12, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, -59  ,  -28, -59  ,  -28, -49  ,  -29, -49  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -12  ,  28, -32  ,  30, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, -66  ,  25, -43  ,  13, -72  ,  16, -70  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, -61  ,  25, -43  ,  20, -66  ,  22, -64  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   28, -32  ,  30, -12  ,  29, -12  ,  21, -37  ,  23, -36  ,  26, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, -79  ,  -11, -78  ,  -11, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, -79  ,  -14, -76  ,  -11, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27, 49  ,  26, 49  ,  26, 35  ,  27, 35  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, 75  ,  25, 74  ,  25, 75  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 32  ,  24, 17  ,  25, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, -43  ,  24, -61  ,  25, -61  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 32  ,  25, 54  ,  11, 75  ,  23, 14  ,  24, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, -79  ,  -26, -41  ,  -26, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, 75  ,  11, 74  ,  21, -37  ,  23, 6  ,  23, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, 61  ,  -28, 61  ,  3, 68  ,  0, 68  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, 3  ,  -26, 51  ,  -27, 51  ,  -27, 3  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, -37  ,  3, 68  ,  -25, 56  ,  -25, 54  ,  1, -78  ,  21, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "char", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, -79  ,  1, -78  ,  -25, 54  ,  -25, -2  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

