--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.4.10
target Corona SDK
extension lua
exportName sheet
exportPath file:///C:/Documents%20and%20Settings/travis/My%20Documents/Corona%20Projects/Gorilla%20Game
sheetSize 512x512
sources 6
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
building6; images/building6.swf; (x=0, y=0); 1; 1; 30; (x=0, y=0); (x=114, y=460); (x=-2, y=-2, w=118, h=464); 1; false; false
building5; images/building5.swf; (x=0, y=0); 1; 1; 30; (x=0, y=0); (x=8, y=231); (x=-2, y=-2, w=12, h=235); 1; false; false
building4; images/building4.swf; (x=0, y=0); 1; 1; 30; (x=0, y=0); (x=49, y=252); (x=-2, y=-2, w=53, h=256); 1; false; false
building3; images/building3.swf; (x=0, y=0); 1; 1; 30; (x=0, y=0); (x=73, y=295); (x=-2, y=-2, w=77, h=299); 1; false; false
building2; images/building2.swf; (x=0, y=0); 1; 1; 30; (x=0, y=0); (x=62, y=329); (x=-2, y=-2, w=66, h=333); 1; false; false
building1; images/building1.swf; (x=0, y=0); 1; 1; 30; (x=0, y=0); (x=65, y=359); (x=-2, y=-2, w=69, h=363); 1; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["building6"] = {
        {
            name="building6-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=118, height=464},
            spriteSourceSize={width=118, height=464},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["building6"])

    frameSets["building5"] = {
        {
            name="building5-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=383, y=0, width=12, height=235},
            spriteSourceSize={width=12, height=235},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["building5"])

    frameSets["building4"] = {
        {
            name="building4-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=330, y=0, width=53, height=256},
            spriteSourceSize={width=53, height=256},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["building4"])

    frameSets["building3"] = {
        {
            name="building3-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=253, y=0, width=77, height=299},
            spriteSourceSize={width=77, height=299},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["building3"])

    frameSets["building2"] = {
        {
            name="building2-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=187, y=0, width=66, height=333},
            spriteSourceSize={width=66, height=333},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["building2"])

    frameSets["building1"] = {
        {
            name="building1-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=118, y=0, width=69, height=363},
            spriteSourceSize={width=69, height=363},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["building1"])


    sheet = sprite.newSpriteSheetFromData("imagessheet.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "building6", 1, 1, 30, 1, 0 - (118/2 + -2), 0 - (464/2 + -2), 118, 464, 0, 0, 118, 464, frameSets["building6"], false)
    newSpriteSet(sheet, "building5", 2, 1, 30, 1, 0 - (12/2 + -2), 0 - (235/2 + -2), 12, 235, 0, 0, 12, 235, frameSets["building5"], false)
    newSpriteSet(sheet, "building4", 3, 1, 30, 1, 0 - (53/2 + -2), 0 - (256/2 + -2), 53, 256, 0, 0, 53, 256, frameSets["building4"], false)
    newSpriteSet(sheet, "building3", 4, 1, 30, 1, 0 - (77/2 + -2), 0 - (299/2 + -2), 77, 299, 0, 0, 77, 299, frameSets["building3"], false)
    newSpriteSet(sheet, "building2", 5, 1, 30, 1, 0 - (66/2 + -2), 0 - (333/2 + -2), 66, 333, 0, 0, 66, 333, frameSets["building2"], false)
    newSpriteSet(sheet, "building1", 6, 1, 30, 1, 0 - (69/2 + -2), 0 - (363/2 + -2), 69, 363, 0, 0, 69, 363, frameSets["building1"], false)

    local shapes = {}
    shapes["building6"] = {

    }
    shapes["building5"] = {

    }
    shapes["building4"] = {

    }
    shapes["building3"] = {

    }
    shapes["building2"] = {

    }
    shapes["building1"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
